name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # set up golang environment
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.3'
          
      - run: go version

      # go test
      - name: Unit test
        run: go test ./...

      # build
      - name: Build
        run: |
          chmod +x build.sh
          bash build.sh
          mkdir -p build-binary
          cp -r build omil
          tar -czvf omil-$(git rev-parse --short HEAD).tar.gz omil
          mv omil-$(git rev-parse --short HEAD).tar.gz build-binary

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: omil-build
          path: build

      - name: Upload to OSS
        id: upload_to_oss
        uses: tvrcgo/upload-to-oss@v0.1.1
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shenzhen
          bucket: build-binary
          asset-path: ./build-binary
          target-path: /github-actions/omil/unstable

      - name: Build binary download URL
        run: echo 'Omil binary url:' ${{steps.upload_to_oss.outputs.url}}
