name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build-job.yml

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build binary download URL
        run: echo 'Omil binary url:' ${{ needs.build.outputs.binary_url }}
