name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Lint
        run: |
          go fmt ./...
          go vet ./...

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20', '1.21']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test
        run: go test -v ./...

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  build:
    needs: [lint, test, security]
    uses: ./.github/workflows/reusable-build.yml

  upload:
    needs: build
    uses: ./.github/workflows/reusable-oss-upload.yml
    with:
      target-path: /github-actions/omil/unstable
    secrets:
      OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
      OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}
