name: Publish built binary to Aliyun OSS
on:
  release:
    types: [created]
  push:
    branches: [master]
jobs:
  build:
    uses: ./.github/workflows/build-job.yml

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build binary download URL
        run: echo 'Omil binary url:' ${{ needs.build.outputs.binary_url }}
