name: Publish built binary to Aliyun OSS
on:
  release:
    types: [created]
  push:
    branches: [master]
jobs:
  build:
    uses: ./.github/workflows/shared.yml
    with:
      target_path: /github-actions/omil/stable
    secrets: inherit
