name: Release
on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

  upload:
    needs: build
    uses: ./.github/workflows/reusable-oss-upload.yml
    with:
      target-path: /github-actions/omil/stable
    secrets:
      OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
      OSS_KEY_SECRET: ${{ secrets.OSS_KEY_SECRET }}

  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: github-changelog-generator/github-changelog-generator@v1.16.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
