name: Build Omil Binary
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache: true

      - name: Build
        run: |
          chmod +x build.sh
          bash build.sh
          mkdir -p build-binary
          cp -r build omil
          tar -czvf omil-$(git rev-parse --short HEAD).tar.gz omil
          mv omil-$(git rev-parse --short HEAD).tar.gz build-binary

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: omil-build
          path: build-binary
